[project]
authors = [{ name = "Houston Bova", email = "houston.bova@gmail.com" }]
dynamic = ["version"]
readme = "README.md"
license = {file = "LICENSE"}
name = "roam-unofficial"
requires-python = ">=3.10"

[tool.black]
line-length = 80

[tool.ruff]
fix = true
line-length = 80
